### ISSUE TITLE
App use with wowza 

### ISSUE THREAD

**Issue by gurkanus** [slavavdovichenko/MediaLibDemos#21]
We are using your application and we are able to run in on DM cloud but wowza servers need four parameters (url, stream address, user name and password) Is there any way to send those parameters to the app? Is there anyone who uses wowza?

**Comment by gkhnaydn** [comment]
try " [socket connect: serverUrl andParams:@[userName,password]] " to connect to wowza with authentication before publish type line instead of " _stream.parameters = @[@"userName", @"passwd"]; " . may be it s too late for answer however many people wonder how to connect to the server with authentication and use the params. unfortunately there is no information about this subject, i mean, neither authentication nor params for client side. i hope it will be helpful for authentication.
